server:
  port: 8090
  servlet:
    context-path: /consumer
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      server-addr: nacos-server.nacos.svc.cluster.local
      username: nacos
      password: nacos