server:
  port: 8091
  servlet:
    context-path: /prod
spring:
  application:
    name: prod-service
  cloud:
    nacos:
      server-addr: localhost:30101
      username: nacos
      password: nacos