server:
  port: 8091
  servlet:
    context-path: /auth
spring:
  application:
    name: auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-read.mysql.svc.cluster.local:3306/sys_threec?useSSL=false&serverTimezone=UTC
    username: root
    password: MSStarForever*00
logging:
  level:
    com.threec.dao: debug
    org:
      springframework:
        security: DEBUG
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.threec.auth.entity

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days